const spacing = {
  'quarter':           '0.25rem',
  'half':              '0.5rem',
  'three-quarters':    '0.75rem',
  DEFAULT:             '1rem',
  'one-and-a-half':    '1.5rem',
  'two':               '2rem',
  'two-and-a-half':    '2.5rem',
  'three':             '3rem',
  'three-and-a-half':  '3.5rem',
  'four':              '4rem',
  'four-and-a-half':   '4.5rem',
  'five':              '5rem',
  'five-and-a-half':   '5.5rem',
  'six':               '6rem',
  'six-and-a-half':    '6.5rem',
  'none':              '0',
}

module.exports = {
  theme: {
    margin: {
      ...spacing,
      'auto': 'auto',
    },
    padding: {
      ...spacing,
    },
    screens: {
      sm: '25rem',
      md: '48rem',
      lg: '64rem',
      xl: '75rem',
    },
    fontSize: {
      xs:    '12px',
      sm:    '14px',
      base:  '16px',
      lg:    '18px',
      xl:    '21px',
      '2xl': '27px',
      '3xl': '34px',
      '4xl': '42px',
      '5xl': '48px',
    },
    leading: {
      tighter: 1.1,
      tight:   1.28,
      normal:  1.414,
      relaxed: 1.6,
      loose:   2.0,
    },
    tracking: {
      tighter:  '-0.035em',
      tight:    '-0.025em',
      normal:   '-0.011em',
      wide:     '0.1em',
    },
    fontWeight: {
      thin:       '100',
      extralight: '200',
      light:      '300',
      normal:     '400',
      medium:     '500',
      semibold:   '600',
      bold:       '700',
      extrabold:  '800',
      black:      '900',
    },
    fontFamily: {
      'body': '-apple-system, sans-serif',
      'code': 'Monaco, monospace',
    },
    opacity: {
      none: '0',
      quarter: '0.25',
      half: '0.5',
      'three-quarters': '0.75',
    },
    gap: {
      ...spacing,
    },
    gridTemplateColumns: {
      '1':  'repeat(1, minmax(0, 1fr))',
      '2':  'repeat(2, minmax(0, 2fr))',
      '3':  'repeat(3, minmax(0, 3fr))',
      '4':  'repeat(4, minmax(0, 4fr))',
      '5':  'repeat(5, minmax(0, 5fr))',
      '6':  'repeat(6, minmax(0, 6fr))',
      '7':  'repeat(7, minmax(0, 7fr))',
      '8':  'repeat(8, minmax(0, 8fr))',
      '9':  'repeat(9, minmax(0, 9fr))',
      '10': 'repeat(10, minmax(0, 10fr))',
      '11': 'repeat(11, minmax(0, 11fr))',
      '12': 'repeat(12, minmax(0, 12fr))',
    },
    gridColumn: {
      '1':  'span 1 / span 1',
      '2':  'span 2 / span 2',
      '3':  'span 3 / span 3',
      '4':  'span 4 / span 4',
      '5':  'span 5 / span 5',
      '6':  'span 6 / span 6',
      '7':  'span 7 / span 7',
      '8':  'span 8 / span 8',
      '9':  'span 9 / span 9',
      '10': 'span 10 / span 10',
      '11': 'span 11 / span 11',
      '12': 'span 12 / span 12',
    },
    order: {
      '1':  '1',
      '2':  '2',
      '3':  '3',
      '4':  '4',
      '5':  '5',
      '6':  '6',
      '7':  '7',
      '8':  '8',
      '9':  '9',
      '10': '10',
      '11': '11',
      '12': '12',
    },
    width: {
      auto: 'auto',
      full: '100%',
    },
    height: {
      auto: 'auto',
      full: '100%',
    },
    zIndex: {
      wallpaper: 0,
      content: 10,
      header: 20,
      footer: 20,
      overlay: 30,
      dropdown: 40,
      navigation: 50,
      modal: 60,
      notification: 70,
    },
  },
  corePlugins: [],
  plugins: [
    require('./plugins/variants/responsive'),
    require('./plugins/variants/no-js'),
    require('./plugins/base/flex'),
    require('./plugins/utilities/grid'),
    require('./plugins/utilities/typography'),
    require('./plugins/utilities/margin'),
    require('./plugins/utilities/opacity'),
    require('./plugins/utilities/order'),
    require('./plugins/utilities/padding'),
    require('./plugins/utilities/font-size'),
    require('./plugins/utilities/font-family'),
    require('./plugins/utilities/font-weight'),
    require('./plugins/utilities/leading'),
    require('./plugins/utilities/tracking'),
    require('./plugins/utilities/width'),
    require('./plugins/utilities/height'),
    require('./plugins/utilities/z-index'),
    require('./plugins/base/kitchen-sink'),
  ],
}
